'use strict';
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('user', {
    uin: DataTypes.BIGINT,
    password: DataTypes.STRING,
    realName: DataTypes.STRING,
    company: DataTypes.STRING,
    platform: DataTypes.STRING,
    userId: DataTypes.STRING,
    ava: DataTypes.STRING,
    aodianUin: DataTypes.BIGINT,
    aodianAccessId: DataTypes.STRING,
    aodianAccessKey: DataTypes.STRING,
    aodianUinPStream: DataTypes.BIGINT,
    aodianAccessIdPStream: DataTypes.STRING,
    aodianAccessKeyPStream: DataTypes.STRING,
    lssApp: DataTypes.STRING,
    lssAppPStream: DataTypes.STRING,
    lpsApp: DataTypes.STRING,
    broadcastMakeHsmsGroupId: DataTypes.STRING,
    authStatus: DataTypes.INTEGER,
    registerTime: DataTypes.BIGINT,
    lastLoginTime: DataTypes.BIGINT,
    lcpsUsedTime: DataTypes.BIGINT,
    accountStatus: DataTypes.INTEGER,
    dmsKeyInfo: DataTypes.STRING,
    msgDmsKey: DataTypes.STRING,
    userType: DataTypes.INTEGER,
    userFrom: DataTypes.INTEGER,
    broadcastMakeType: DataTypes.INTEGER,
    liveProgramMpsId: DataTypes.BIGINT,
    tvProgramMpsId: DataTypes.BIGINT,
    radioProgramMpsId: DataTypes.BIGINT,
    businessManagerId: DataTypes.BIGINT,
    status: DataTypes.INTEGER,
    maxrecordduration: DataTypes.BIGINT,
    newsTitle: DataTypes.STRING,
    rbacStatus: DataTypes.INTEGER,
    isExamine: DataTypes.INTEGER,
    leagueStatus: DataTypes.INTEGER,
    cname: DataTypes.STRING,
    cnameStatus: DataTypes.INTEGER,
    agencyLoginBackground: DataTypes.STRING,
    tvLssApp: DataTypes.STRING,
    cmsExamine: DataTypes.INTEGER,
    tvStorage: DataTypes.INTEGER,
    radioStorage: DataTypes.INTEGER,
    projectVersion: DataTypes.INTEGER,
    liveVersion: DataTypes.INTEGER,
    authKey: DataTypes.STRING,
    roleInit: DataTypes.INTEGER,
    twAuditing: DataTypes.INTEGER,
    menuType: DataTypes.INTEGER,
    version: DataTypes.STRING,
  }, 
  {
    freezeTableName : true,
    timestamps : false
  });
  User.associate = function(models) {
    // associations can be defined here
  };
  return User;
};